### ISSUE TITLE
can't copy 'Pfeature/ONTAINER-LICENSE'

### ISSUE THREAD

**Issue by Khaled013** [raghavagps/Pfeature#6]
>>>!python3 setup.py install 
/usr/local/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
  warnings.warn(msg)
running install
running build
running build_py
copying Pfeature/__init__.py -> build/lib/Pfeature
error: can't copy 'Pfeature/ONTAINER-LICENSE': doesn't exist or not a regular file

**Comment by 688spiderbin** [comment]
I got same error, have you figure out？

**Comment by Khaled013** [comment]
> 

No, I didn't I just used other tools
you can use iFeature or iLearn
