### ISSUE TITLE
problem in using the standalone package : permission error

### ISSUE THREAD

**Issue by GhsJahanmir** [raghavagps/Pfeature#8]
Hi,

I faced an error:"PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'tempfile_out'"  when trying to run the command:  pfeature_comp.py -i protein.fa    in anaconda prompt.

any suggestion/solution is appreciated,

Thanks,
Jahanmir

**Comment by debaratipaul4** [comment]
Facing the same issue..Is this resolved ?

**Comment by co1yzha** [comment]
Any updates on this? It works fine on Mac, but once installed on Windows, it hits the "PermissionErro on os.remove('tempfile_out')"

**Comment by sumeetpatiyal** [comment]
Dear All,

One good way to avoid that error to remove or comment the line os.remove('tempfile_out') from the code. That would rectify your error.

Thank You
Sumeet Patiyal
