### ISSUE TITLE
Installation of Pfeature

### ISSUE THREAD

**Issue by agboken** [raghavagps/Pfeature#9]
Hi 
I have been trying to install this package on my Python but have never succeeded in doing that for over 5 months now.
please help me out, I really need this package for my PhD research work.
Thanks

**Comment by sumeetpatiyal** [comment]
Dear Agboken,

I sincerely apologize for the late reply. You can download the standalone package and run your queries. The standalone package would be much faster.

Thank You
Sumeet Patiyal
